### ISSUE TITLE
Problems about public parameters

### ISSUE THREAD

**Issue by huyuncong** [alinush/libaad-ccs2019#1]
I am trying to re-run the microbenchmark for append and uses the public parameters in "libaad-ccs2019/public-params/8192/". 
But it says there are no enough public parameters. 
I was wondering how to reproduce the result in "libaad-ccs2019/experiments/2019-02-02-aad-append-time-n-8192-b-*".
Here are the command I was using and the error message:
<img width="1639" alt="issue" src="https://user-images.githubusercontent.com/7484604/79544154-6a220500-8043-11ea-8290-4fa8a1db0cd0.png">

**Comment by alinush** [comment]
Hey Yuncong,

The AAD data structure needs `n * secParam * 4` public params. That's why it's expecting more when you're testing on `n = 8192`.

Just use this script [here](https://github.com/alinush/libaad-ccs2019/blob/master/scripts/linux/generate-qpke-params.sh) to generate more params:

```
cd libaad-ccs2019/
source scripts/linux/set-env.sh release
mkdir public-params/$((512*1024))/
cd $_
generate-qpke-params.sh $((512*1024)) $((512*1024))
```

Now, you should have enough public params in `libaad-ccs2019/public-params/$((512*1024))/` to run the benchmark.

**Comment by huyuncong** [comment]
That works! Thanks so much!
But it seems the default security parameter is 128, so I have to generate public parameters for 8192X128X4=4194304.

**Comment by alinush** [comment]
Indeed, hence your error above :)
